### ISSUE TITLE
Projection not working

### ISSUE THREAD

**Issue by andersonfaaria** [eps696/stylegan2#3] opened 2020-08-11 23:54 UTC
If I use the vgg16_zhang_perceptual that is available in this repository I get the following error message:
![image](https://user-images.githubusercontent.com/8560144/89960185-a7bf2500-dc14-11ea-86e6-cb2cf7224db4.png)

I checked the src/projection.py file and notice there was a commented drive to download and I tried to re-download that version, which lead me to the following error message:
![image](https://user-images.githubusercontent.com/8560144/89960168-9c6bf980-dc14-11ea-815e-55d2f2735f50.png)

Can you please provide a working version or give a more in depth example on how you're using it?
I put my pkl (only G) file in the models folder and tried to run giving the both parameters you ask in .bat file.

**Comment by eps696** [comment] 2020-08-13 00:45
first issue relates to Git LFS specifics for dealing with big files (briefly remarked on readme): when cloning the repo, you get only a stub file; one need to navigate to that file on github and download the real one by 'download' button. i've put back the original download option in case the vgg file is missed or wrong size.

second problem is more obscure for me, can't reproduce it here. those 4 and 3 should relate to the channel (color) count of the images; may it be that your pkl is trained on 4 channels (rgba instead of rgb)? in the meantime the projected images colorspace is cut to rgb during loading.

**Comment by andersonfaaria** [comment] 2020-08-13 00:59
Yes, I'm using a pkl file trained using 4 channels (w/ transparency). In that case I would need use a vgg with 4 channels?
There's any easy way to convert it to 4 channels or do it need to be trained from scratch?

**Comment by eps696** [comment] 2020-08-13 01:30
i have no idea of such easy ways, and retraining vgg sounds like a total overkill for this task. at the moment i'll just drop the 4th channel, so that the shapes fit.

**Comment by eps696** [comment] 2020-08-13 01:44
should be fixed now, let me know if it worked.

**Closed as completed** 2020-08-25 15:50 UTC
